[entities.user]
api_id_prefix = "usr"
    [entities.user.fields]
    name = { type = "string" }
    email = { type = "string", required = true }
    password = { type = "password_hash", required = true }
